version: '3.7'

services:
    python:
        build:
            dockerfile: ./Dockerfile
        working_dir: /app
        command: python3 -m flask --app app/app.py run --host=0.0.0.0 --debug
        depends_on:
            - postgres
        volumes: 
            - ./source:/app
        env_file:
            - .env  
        ports:
            - ${APP_PORT}:5000
        networks: 
            - python-network
            - postgres-network
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 512M
                reservations:
                    memory: 128M

    # cron:
    #     build:
    #         context: .
    #         dockerfile: ./docker/cron/Dockerfile
    #     depends_on:
    #         - postgres
    #     volumes: 
    #         - ./source:/app
    #     env_file:
    #         - .env
    #     networks:
    #         - cron-network
    #         - postgres-network
    #     deploy:  # Adicione deploy ao cron se for usá-lo
    #         resources:
    #             limits:
    #                 cpus: "0.5"
    #                 memory: 256M
    #             reservations:
    #                 memory: 64M


    postgres:
        image: postgres:alpine
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5433:5432
        networks:
            - postgres-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M
                reservations:
                    memory: 64M

    # pgadmin:
    #     image: dpage/pgadmin4
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #     volumes:
    #         - ./docker/pgadmin/pgadmin4/servers.json:/pgadmin4/servers.json
    #     ports:
    #         - 5050:80
    #     networks:
    #         - pgadmin-network
    #         - postgres-network
    #     deploy: # Adicione deploy ao pgadmin se for usá-lo
    #         resources:
    #             limits:
    #                 cpus: "0.25"
    #                 memory: 128M
    #             reservations:
    #                 memory: 32M


volumes:
    postgres-volume:
        driver: local

networks:
    python-network:
        driver: bridge
    cron-network:
        driver: bridge
    postgres-network:
        driver: bridge
    pgadmin-network:
        driver: bridge